/*
# Lumen Socratic Learning OS — Core Schema

## Purpose
Single-tenant (no sign-in) schema for the Lumen learning app. The app reads and writes as the anon role for its entire lifetime, so every policy lists `anon, authenticated` and ownership is intentionally public/shared within this app instance.

## New Tables
1. `profiles` — Local learner profile (confidence, cognitive load, diagnostic score).
   - id (int, pk), display_name (text), diagnostic_score (int), confidence (int), cognitive_load (text), updated_at (timestamptz)
2. `synthesized_paths` — Socratic courses generated by the synthesizer.
   - id (uuid pk), title (text), phase (text), axioms (jsonb), modules (jsonb), socratic_challenge (text), created_at (timestamptz)
3. `unit_progress` — Per-unit progress percentages for synthesized paths.
   - id (uuid pk), path_id (uuid fk -> synthesized_paths), unit_id (text), progress (int 0-100), updated_at (timestamptz)
4. `chat_messages` — Persistent conversation messages with the Lumen tutor.
   - id (uuid pk), sender (text: 'user'|'lumen'), text (text), action_taken (text nullable), created_at (timestamptz)
5. `diagnostic_attempts` — Records of adaptive diagnostic quiz attempts.
   - id (uuid pk), subject (text), final_level (int), questions_answered (int), correct_count (int), created_at (timestamptz)

## Security
- RLS enabled on every table.
- All tables allow anon + authenticated full CRUD because this is a single-tenant app with no sign-in (data is intentionally shared/public within the app instance).
*/

CREATE TABLE IF NOT EXISTS profiles (
  id integer PRIMARY KEY DEFAULT 1,
  display_name text NOT NULL DEFAULT 'Learner',
  diagnostic_score integer NOT NULL DEFAULT 0,
  confidence integer NOT NULL DEFAULT 50,
  cognitive_load text NOT NULL DEFAULT 'Optimal',
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_profiles" ON profiles;
CREATE POLICY "anon_select_profiles" ON profiles FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_profiles" ON profiles;
CREATE POLICY "anon_insert_profiles" ON profiles FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_profiles" ON profiles;
CREATE POLICY "anon_update_profiles" ON profiles FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_profiles" ON profiles;
CREATE POLICY "anon_delete_profiles" ON profiles FOR DELETE
  TO anon, authenticated USING (true);


CREATE TABLE IF NOT EXISTS synthesized_paths (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  phase text NOT NULL DEFAULT 'High School',
  axioms jsonb NOT NULL DEFAULT '[]'::jsonb,
  modules jsonb NOT NULL DEFAULT '[]'::jsonb,
  socratic_challenge text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE synthesized_paths ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_paths" ON synthesized_paths;
CREATE POLICY "anon_select_paths" ON synthesized_paths FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_paths" ON synthesized_paths;
CREATE POLICY "anon_insert_paths" ON synthesized_paths FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_paths" ON synthesized_paths;
CREATE POLICY "anon_update_paths" ON synthesized_paths FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_paths" ON synthesized_paths;
CREATE POLICY "anon_delete_paths" ON synthesized_paths FOR DELETE
  TO anon, authenticated USING (true);


CREATE TABLE IF NOT EXISTS unit_progress (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  path_id uuid REFERENCES synthesized_paths(id) ON DELETE CASCADE,
  unit_id text NOT NULL,
  progress integer NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE unit_progress ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_unit_progress" ON unit_progress;
CREATE POLICY "anon_select_unit_progress" ON unit_progress FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_unit_progress" ON unit_progress;
CREATE POLICY "anon_insert_unit_progress" ON unit_progress FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_unit_progress" ON unit_progress;
CREATE POLICY "anon_update_unit_progress" ON unit_progress FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_unit_progress" ON unit_progress;
CREATE POLICY "anon_delete_unit_progress" ON unit_progress FOR DELETE
  TO anon, authenticated USING (true);


CREATE TABLE IF NOT EXISTS chat_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sender text NOT NULL CHECK (sender IN ('user','lumen')),
  text text NOT NULL,
  action_taken text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_chat" ON chat_messages;
CREATE POLICY "anon_select_chat" ON chat_messages FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_chat" ON chat_messages;
CREATE POLICY "anon_insert_chat" ON chat_messages FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_chat" ON chat_messages;
CREATE POLICY "anon_update_chat" ON chat_messages FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_chat" ON chat_messages;
CREATE POLICY "anon_delete_chat" ON chat_messages FOR DELETE
  TO anon, authenticated USING (true);


CREATE TABLE IF NOT EXISTS diagnostic_attempts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  subject text NOT NULL,
  final_level integer NOT NULL DEFAULT 3,
  questions_answered integer NOT NULL DEFAULT 0,
  correct_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE diagnostic_attempts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_diag" ON diagnostic_attempts;
CREATE POLICY "anon_select_diag" ON diagnostic_attempts FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_diag" ON diagnostic_attempts;
CREATE POLICY "anon_insert_diag" ON diagnostic_attempts FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "anon_update_diag" ON diagnostic_attempts;
CREATE POLICY "anon_update_diag" ON diagnostic_attempts FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_delete_diag" ON diagnostic_attempts;
CREATE POLICY "anon_delete_diag" ON diagnostic_attempts FOR DELETE
  TO anon, authenticated USING (true);


-- Seed a default profile row if none exists
INSERT INTO profiles (id, display_name)
SELECT 1, 'Learner'
WHERE NOT EXISTS (SELECT 1 FROM profiles WHERE id = 1);
